<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		
		<TargetFrameworks>net8.0-android;net8.0-ios;net8.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net8.0-tizen</TargetFrameworks> -->

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType>Exe</OutputType>
		<RootNamespace>ColetorA41</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

		

		<!-- Display name -->
		<ApplicationTitle>ColetorA41</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.coletora41</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<WindowsSdkPackageVersion>10.0.19041.41</WindowsSdkPackageVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">11.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">13.1</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
		<NullabilityInfoContextSupport>true</NullabilityInfoContextSupport>
		<AndroidSigningKeyStore>Diebold.keystore</AndroidSigningKeyStore>
		
	</PropertyGroup>

	<!--PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-android|AnyCPU'">
	  <Debugger>Xamarin</Debugger>
	  <AndroidUseAapt2>True</AndroidUseAapt2>
	  <AndroidCreatePackagePerAbi>False</AndroidCreatePackagePerAbi>
	  <AndroidPackageFormat>apk</AndroidPackageFormat>
	</PropertyGroup>
	-->

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-android|AnyCPU'">
	  <Debugger>Xamarin</Debugger>
	  <AndroidPackageFormat>apk</AndroidPackageFormat>
	  <AndroidUseAapt2>True</AndroidUseAapt2>
	  <AndroidCreatePackagePerAbi>False</AndroidCreatePackagePerAbi>
	  <AndroidKeyStore>False</AndroidKeyStore>
	  <AndroidSigningStorePass>junior2006</AndroidSigningStorePass>
	  <AndroidSigningKeyAlias>coletora41</AndroidSigningKeyAlias>
	  <AndroidSigningKeyPass>123456</AndroidSigningKeyPass>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-android|AnyCPU'">
	  <AndroidKeyStore>False</AndroidKeyStore>
	  <AndroidSigningStorePass>junior2006</AndroidSigningStorePass>
	  <AndroidSigningKeyAlias>coletora41</AndroidSigningKeyAlias>
	  <AndroidSigningKeyPass>123456</AndroidSigningKeyPass>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\dn_icon.svg" ForegroundFile="Resources\AppIcon\dn_icon.svg" Color="#FFFFFF" />

		<!-- Splash Screen -->
		<!-- MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" /-->

		<MauiSplashScreen Include="Resources\Splash\dn_logo2.svg" Color="#FFFFFF" BaseSize="128,128" />
		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="ViewModel\CalculoDadosNF.cs" />
	  <Compile Remove="ViewModel\CalculoDadosNFBase.cs" />
	  <Compile Remove="Views\Calculo\ExtrakitView - Cópia.xaml.cs" />
	  <Compile Remove="Views\Calculo\ResumoDetalheItem - Cópia.xaml.cs" />
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Remove="Views\Calculo\ResumoDetalheItem - Cópia.xaml" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="appsettings.desenv.json" />
	  <None Remove="appsettings.prod.json" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="appsettings.prod.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="9.1.0" />
		<PackageReference Include="CommunityToolkit.Maui.Core" Version="9.1.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.1" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.1" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="9.0.1" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.92" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.100" />
		
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="appsettings.desenv.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Views\Calculo\ResumoDetalhePagto.xaml.cs">
	    <DependentUpon>ResumoDetalhePagto.xaml</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="Microsoft.Maui.Controls" Version="8.0.92" />
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Views\Calculo\DadosNF.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Calculo\EstabTec.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Calculo\ExtrakitView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Calculo\LeituraENC.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Calculo\LeituraPagtos.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Calculo\LoadingCalculo.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Calculo\LoginAlmoxa.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Calculo\Resumo.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Calculo\ResumoDetalheEntrada.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Calculo\ResumoDetalhePagto.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Calculo\ResumoDetalhe.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Calculo\ResumoDetalheItem.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Calculo\ZoomTransporte.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Erro.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Loading.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Login.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\MainPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Mensagem.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\MensagemSimNao.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Monitor\Embalagem.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Monitor\EmbalagemLoading.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Monitor\EmbalagemPrimeiraNota.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Monitor\Processos.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Monitor\Reparo.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Monitor\ReparoEdicaoItemReparo.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Monitor\ResumoFinal.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

</Project>
